### ISSUE TITLE
Unhandled exception System.NullReferenceException in ArchiveReader.cs

### ISSUE THREAD

**Issue by droh99** [cube-soft/Cube.FileSystem.SevenZip#2]
Hi,

at first, thank you for this wrapper. When testing my app where I used your wrapper, I probably found a bug. There is following code in my app:
`                    using (var extractor = new ArchiveReader(inputpath))
                    {
                            extractor.Extract(outputpath);
                        }`

When I try to call Extract method via extractor object, following exception in Cube.FileSystem.SevenZip.dll is thrown:

> Exception thrown: 'System.NullReferenceException' in Cube.FileSystem.SevenZip.dll
**_callback** was null.

Problematic code is in your ArchiveReader.cs file, line 264. _callback object is null and it is not possible to dispose it:
`        protected override void Dispose(bool disposing)
        {
            _callback.Dispose();
            _module.Close();
            _core.Dispose();
        }`

Problematic archive attached.

[Google%20Chrome%20Extension.zip](https://github.com/cube-soft/Cube.FileSystem.SevenZip/files/2671379/Google.20Chrome.20Extension.zip)

Thank you,
David

**Comment by clown** [comment]
Thank you for your report.
I'll confirm it by using the attached archive.

**Comment by clown** [comment]
Fix to check null when disposing (commit b81da6b82a1cfb74ba7e6f41fbfd1655a12d7b04, NuGet [1.14.0](https://www.nuget.org/packages/Cube.FileSystem.SevenZip/1.14.0)).
I think there is another problem because the callback field is never null in the usual case, and I have not found the problem yet...
