### ISSUE TITLE
if possible, please remove dependices

### ISSUE THREAD

**Issue by deltaone** [cube-soft/Cube.FileSystem.SevenZip#3]
please make standalone library, 6 dll for manipulating .7z is too many l)

**Comment by deltaone** [comment]
list of files from Cube.Core and Cube.FileSystem for build without 3rd party libs
``Cube.Core\AssemblyReader.cs 0DF253E9
Cube.Core\Collections\KeyValuePair.cs 3DECE9EF
Cube.Core\Collections\LambdaEqualityComparer.cs CCEB26E8
Cube.Core\DisposableBase.cs A450FEE2
Cube.Core\Events\QueryEventArgs.cs C6CDAB21
Cube.Core\Exceptions.cs 68433177
Cube.Core\Extensions\StringExtension.cs B55BAA7A
Cube.Core\OnceAction.cs 64FF07A1
Cube.Core\Query.cs 11DC9B74
Cube.FileSystem\FailedEventArgs.cs 9CE3CCCF
Cube.FileSystem\Information.cs F91E6304
Cube.FileSystem\Io.cs 5B883BCD
Cube.FileSystem\PathFilter.cs 215B01DE
Cube.FileSystem\Refreshable.cs D5990E53
Cube.FileSystem\RefreshableInfo.cs 39E60573

**Comment by clown** [comment]
Sorry, but  I won't do that because I consider the Cube.FileSystem.SevenZip as one of Cube.* libraries.
