### ISSUE TITLE
missing test mode interface, please add option for testing archives

### ISSUE THREAD

**Issue by deltaone** [cube-soft/Cube.FileSystem.SevenZip#4]
find only extract
        public void Extract(string directory, IProgress<Report> progress)
        {
            using (var cb = Create(directory, progress))
            {
                _module.Extract(null, uint.MaxValue, 0, cb);
                Terminate(cb.Result, cb.Exception);
            }
        }

_module.Extract(null, uint.MaxValue, 0, cb);
===>
<param name="test">test != 0 means "test files operation"</param>

test flag always is zero

Changing 0 to 1 throwing exception ;(

**Comment by clown** [comment]
OK, I'll add an interface for testing.

**Comment by clown** [comment]
I added the following methods. ArchiveReader and ArchiveItem run in test mode when you omit the directory path.

ArchiveReader.Extract();
ArchiveReader.Extract(IProgress<Report>);
ArchiveItem.Extract();
ArchiveItem.Extract(IProgress<Report>);
