### ISSUE TITLE
Please map CRC from ItemPropId to ArchiveItem, TY!

### ISSUE THREAD

**Issue by deltaone** [cube-soft/Cube.FileSystem.SevenZip#5]
%SUBJ%

**Comment by deltaone** [comment]
Please apply to libs if i do right fixes, TY!

Cube.FileSystem.SevenZip\Details\ArchiveItemController.cs
>       public void Invoke(RefreshableInfo src)
>         {
>             RawName   = GetPath(src.Source);
>             Encrypted = Get<bool>(src.Source, ItemPropId.Encrypted);
> 
>             src.Exists         = true;
>             src.IsDirectory = Get<bool>(src.Source, ItemPropId.IsDirectory);
> 			src.Attributes     = (System.IO.FileAttributes)Get<uint>(src.Source, ItemPropId.Attributes);
>             src.Length         = (long)Get<ulong>(src.Source, ItemPropId.Size);
>             src.CreationTime   = Get<DateTime>(src.Source, ItemPropId.CreationTime);
>             src.LastWriteTime  = Get<DateTime>(src.Source, ItemPropId.LastWriteTime);
>             src.LastAccessTime = Get<DateTime>(src.Source, ItemPropId.LastAccessTime);
> 
> 			// TODO: $d1
> 			src.CRC = Get<uint>(src.Source, ItemPropId.Crc);
> 

 Cube.FileSystem\Information.cs
>        public DateTime LastAccessTime => Core.LastAccessTime;
> 
> 
> 		// TODO: $d1
> 		public uint CRC => Core.CRC;
> 
>         #endregion
> 
>         #region Methods
Cube.FileSystem\RefreshableInfo.cs

>         public DateTime LastAccessTime { get; set; }
> 
> 		// TODO: $d1
> 		public uint CRC { get; set; }
> 
> 		#endregion

**Comment by clown** [comment]
Add Crc property in the ArchiveItem class.
see commit dfd27a4c7217535e4446752de96454cb0ea9747d

I found that the 7-Zip module always returns zero in some archives (e.g. the following files in the [Examples](https://github.com/cube-soft/Cube.FileSystem.SevenZip/tree/master/Tests/Examples) folder).

* Sample.tar
* Sample.tar.bz2
* Sample.tar.lzma
* Sample.tar.z
* Sample.txz
* Sample.txt.bz2
* Sample.txt.xz
