### ISSUE TITLE
Please add check for zero filled / zero sized archives

### ISSUE THREAD

**Issue by deltaone** [cube-soft/Cube.FileSystem.SevenZip#6]
When use zero filled .rar file
> 				using(var archive = new ArchiveReader(file.FullName))
> 					{
> 						foreach(var item in archive.Items)

Getting uncatchable  exception in

d:\work\is-keeper\src\Lib\Cube.FileSystem.SevenZip\Details\ArchiveItemController.cs
>        private T Get<T>(string src, ItemPropId pid)
>         {
>             var var = new PropVariant();
>             _archive.GetProperty((uint)Index, pid, ref var);

**Comment by clown** [comment]
I'll confirm the issue.

**Comment by clown** [comment]
I fixed the issue and tested with the following *.rar archives.

* [SampleEmpty.rar](https://github.com/cube-soft/Cube.FileSystem.SevenZip/blob/master/Libraries/Tests/Examples/SampleEmpty.rar) ... zero-byte file only.
* [Sample.rar](https://github.com/cube-soft/Cube.FileSystem.SevenZip/blob/master/Libraries/Tests/Examples/Sample.rar) ... mixed zero-byte file and other files.
